# Generated by Django 4.2.16 on 2024-12-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_customuser_email_alter_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_number', models.CharField(editable=False, max_length=15, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('documents', models.FileField(blank=True, null=True, upload_to='student_documents/')),
                ('fee_paid', models.BooleanField(default=False)),
                ('admission_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
