# Generated by Django 4.2.16 on 2024-12-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_student_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('qualification', models.CharField(max_length=200)),
                ('experience', models.PositiveIntegerField(help_text='Experience in years')),
                ('subjects_taught', models.TextField(help_text='List of subjects taught')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='faculty_pictures/')),
            ],
        ),
    ]
