# Generated by Django 4.2.16 on 2024-12-07 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_course1_remove_schedule_schedule_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
