# Generated by Django 4.2.16 on 2024-12-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_course_batch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='course',
            new_name='courses',
        ),
    ]
