# Generated by Django 4.2.16 on 2024-12-10 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_courses_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='courses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.courses'),
        ),
    ]
