# Generated by Django 4.2.16 on 2024-12-13 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_studentdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=255)),
                ('seating_arrangement', models.TextField(blank=True, help_text='Details about seating arrangement')),
                ('course1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course1')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.studentdetails')),
            ],
        ),
    ]
