# Generated by Django 4.2.16 on 2024-12-13 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='subjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courses'),
        ),
    ]
